language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0

gemfile:
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile

before_script:
  - bundle exec rake db:migrate
  - bundle exec rake app:db:test:prepare

script: bundle exec rake
